### ISSUE TITLE
规范Git提交日志格式

### ISSUE THREAD

**Issue by shafreeck** [distributedio/enjoy-the-team#3]

**Comment by arthurkiller** [comment]
上次说的那个链接可以贴上来

**Comment by arthurkiller** [comment]
https://www.cnblogs.com/daysme/p/7722474.html
FYI

**Comment by arthurkiller** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

https://blog.csdn.net/crazyzhang1990/article/details/41865179

关于 hook

**Comment by shafreeck** [comment]
http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html
from 阮一峰

**Comment by shafreeck** [comment]
AngularJS 提交规范https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.greljkmo14y0

**Comment by arthurkiller** [comment]
我觉得不必全盘照搬，使得提交日志的负担更重了，但是确实需要规范一下提交记录：

* 有一定的格式， 便于 grep
* 如果不是特别大的提交，使用 -m 一行提交； 非常大的改动，使用多行提交之外，应该再 changelog 中可以追溯
* 杜绝没有意义的提交日志： modify， update，更新文件，fix bug 诸如此类
* 多次连续的提交，带有相同的 comment： 使用 git commit ammend 修改提交
* 作为开源项目，使用英文是必要的，因此没有特殊情况，应尽量使用 英文 提交记录

基于以上，我觉得可以有一个总结：

格式：<type> <content> [body]

### type

type用于说明 commit 的类别，只允许使用下面7个标识。

feat：新功能（feature）
fix：修补bug
docs：文档（documentation）
style： 格式（不影响代码运行的变动）
refactor：重构（即不是新增功能，也不是修改bug的代码变动）
test：增加测试
chore：构建过程或辅助工具的变动

### cotent
做了什么事情，关键在于描述清楚。一定要杜绝无意义而且不清晰的提交日志。

动作 + 操作对象 + [结果/影响]

* 以动词开头，使用第一人称现在时，比如change，而不是 __changed或changes__ (这条我经常错)
* 第一个字母小写
* 结尾不加句号（.）

### body
可以按照罗列的方式详细描述更改和影响， 可选项

**Comment by shafreeck** [comment]
> 我觉得不必全盘照搬，使得提交日志的负担更重了

嗯，这里我只是把资料链接贴过来

**Comment by arthurkiller** [comment]
对于常用的英语词汇，我昨天在一个分享上看了一个非常好的总结，我把内容贴出来供大家参考

![image](https://user-images.githubusercontent.com/11133870/59011183-61c73e00-8866-11e9-9a48-dfaafa7339da.png)

![image](https://user-images.githubusercontent.com/11133870/59011211-74417780-8866-11e9-8834-78044cdacd5d.png)

**Comment by shafreeck** [comment]
https://github.com/conventional-changelog/commitlint
lint 工具
